// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: marketdata/v1/market_data.proto

package marketdatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Present empty filters are different from omitted filters.
type ListInstrumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *string                `protobuf:"bytes,1,opt,name=exchange,proto3,oneof" json:"exchange,omitempty"`
	Market        *string                `protobuf:"bytes,2,opt,name=market,proto3,oneof" json:"market,omitempty"`
	Symbol        *string                `protobuf:"bytes,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstrumentsRequest) Reset() {
	*x = ListInstrumentsRequest{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstrumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstrumentsRequest) ProtoMessage() {}

func (x *ListInstrumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstrumentsRequest.ProtoReflect.Descriptor instead.
func (*ListInstrumentsRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{0}
}

func (x *ListInstrumentsRequest) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *ListInstrumentsRequest) GetMarket() string {
	if x != nil && x.Market != nil {
		return *x.Market
	}
	return ""
}

func (x *ListInstrumentsRequest) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *ListInstrumentsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type ListTickersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *string                `protobuf:"bytes,1,opt,name=exchange,proto3,oneof" json:"exchange,omitempty"`
	Market        *string                `protobuf:"bytes,2,opt,name=market,proto3,oneof" json:"market,omitempty"`
	Symbol        *string                `protobuf:"bytes,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTickersRequest) Reset() {
	*x = ListTickersRequest{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTickersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTickersRequest) ProtoMessage() {}

func (x *ListTickersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTickersRequest.ProtoReflect.Descriptor instead.
func (*ListTickersRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{1}
}

func (x *ListTickersRequest) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *ListTickersRequest) GetMarket() string {
	if x != nil && x.Market != nil {
		return *x.Market
	}
	return ""
}

func (x *ListTickersRequest) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

type ListMarketStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *string                `protobuf:"bytes,1,opt,name=exchange,proto3,oneof" json:"exchange,omitempty"`
	Market        *string                `protobuf:"bytes,2,opt,name=market,proto3,oneof" json:"market,omitempty"`
	Symbol        *string                `protobuf:"bytes,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	Window        *string                `protobuf:"bytes,4,opt,name=window,proto3,oneof" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketStatsRequest) Reset() {
	*x = ListMarketStatsRequest{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketStatsRequest) ProtoMessage() {}

func (x *ListMarketStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketStatsRequest.ProtoReflect.Descriptor instead.
func (*ListMarketStatsRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{2}
}

func (x *ListMarketStatsRequest) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *ListMarketStatsRequest) GetMarket() string {
	if x != nil && x.Market != nil {
		return *x.Market
	}
	return ""
}

func (x *ListMarketStatsRequest) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *ListMarketStatsRequest) GetWindow() string {
	if x != nil && x.Window != nil {
		return *x.Window
	}
	return ""
}

// All fields are required by application validation, including both timestamps.
type GetKlinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *string                `protobuf:"bytes,1,opt,name=exchange,proto3,oneof" json:"exchange,omitempty"`
	Market        *string                `protobuf:"bytes,2,opt,name=market,proto3,oneof" json:"market,omitempty"`
	Symbol        *string                `protobuf:"bytes,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	Interval      *string                `protobuf:"bytes,4,opt,name=interval,proto3,oneof" json:"interval,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKlinesRequest) Reset() {
	*x = GetKlinesRequest{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlinesRequest) ProtoMessage() {}

func (x *GetKlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlinesRequest.ProtoReflect.Descriptor instead.
func (*GetKlinesRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{3}
}

func (x *GetKlinesRequest) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *GetKlinesRequest) GetMarket() string {
	if x != nil && x.Market != nil {
		return *x.Market
	}
	return ""
}

func (x *GetKlinesRequest) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *GetKlinesRequest) GetInterval() string {
	if x != nil && x.Interval != nil {
		return *x.Interval
	}
	return ""
}

func (x *GetKlinesRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetKlinesRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type ListInstrumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruments   []*Instrument          `protobuf:"bytes,1,rep,name=instruments,proto3" json:"instruments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstrumentsResponse) Reset() {
	*x = ListInstrumentsResponse{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstrumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstrumentsResponse) ProtoMessage() {}

func (x *ListInstrumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstrumentsResponse.ProtoReflect.Descriptor instead.
func (*ListInstrumentsResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{4}
}

func (x *ListInstrumentsResponse) GetInstruments() []*Instrument {
	if x != nil {
		return x.Instruments
	}
	return nil
}

type ListTickersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickers       []*Ticker              `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTickersResponse) Reset() {
	*x = ListTickersResponse{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTickersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTickersResponse) ProtoMessage() {}

func (x *ListTickersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTickersResponse.ProtoReflect.Descriptor instead.
func (*ListTickersResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{5}
}

func (x *ListTickersResponse) GetTickers() []*Ticker {
	if x != nil {
		return x.Tickers
	}
	return nil
}

type ListMarketStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketStats   []*MarketStats         `protobuf:"bytes,1,rep,name=market_stats,json=marketStats,proto3" json:"market_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketStatsResponse) Reset() {
	*x = ListMarketStatsResponse{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketStatsResponse) ProtoMessage() {}

func (x *ListMarketStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketStatsResponse.ProtoReflect.Descriptor instead.
func (*ListMarketStatsResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{6}
}

func (x *ListMarketStatsResponse) GetMarketStats() []*MarketStats {
	if x != nil {
		return x.MarketStats
	}
	return nil
}

type GetKlinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Market        string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval      string                 `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Klines        []*Kline               `protobuf:"bytes,5,rep,name=klines,proto3" json:"klines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKlinesResponse) Reset() {
	*x = GetKlinesResponse{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKlinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlinesResponse) ProtoMessage() {}

func (x *GetKlinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlinesResponse.ProtoReflect.Descriptor instead.
func (*GetKlinesResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{7}
}

func (x *GetKlinesResponse) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetKlinesResponse) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetKlinesResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetKlinesResponse) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *GetKlinesResponse) GetKlines() []*Kline {
	if x != nil {
		return x.Klines
	}
	return nil
}

// Decimals are exact canonical strings, limited to 1,024 characters by the application.
// Timestamp fields track presence. The application guarantees updated_at.
type Instrument struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Exchange               string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Market                 string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Symbol                 string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BaseAsset              string                 `protobuf:"bytes,4,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QuoteAsset             string                 `protobuf:"bytes,5,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	Status                 string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	PriceTick              string                 `protobuf:"bytes,7,opt,name=price_tick,json=priceTick,proto3" json:"price_tick,omitempty"`
	QtyStep                string                 `protobuf:"bytes,8,opt,name=qty_step,json=qtyStep,proto3" json:"qty_step,omitempty"`
	MinQty                 *string                `protobuf:"bytes,9,opt,name=min_qty,json=minQty,proto3,oneof" json:"min_qty,omitempty"`
	MaxQty                 *string                `protobuf:"bytes,10,opt,name=max_qty,json=maxQty,proto3,oneof" json:"max_qty,omitempty"`
	MinNotional            *string                `protobuf:"bytes,11,opt,name=min_notional,json=minNotional,proto3,oneof" json:"min_notional,omitempty"`
	FundingIntervalSeconds *int64                 `protobuf:"varint,12,opt,name=funding_interval_seconds,json=fundingIntervalSeconds,proto3,oneof" json:"funding_interval_seconds,omitempty"`
	DelistingTime          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=delisting_time,json=delistingTime,proto3" json:"delisting_time,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Instrument) Reset() {
	*x = Instrument{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instrument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument) ProtoMessage() {}

func (x *Instrument) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument.ProtoReflect.Descriptor instead.
func (*Instrument) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{8}
}

func (x *Instrument) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Instrument) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *Instrument) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Instrument) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *Instrument) GetQuoteAsset() string {
	if x != nil {
		return x.QuoteAsset
	}
	return ""
}

func (x *Instrument) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Instrument) GetPriceTick() string {
	if x != nil {
		return x.PriceTick
	}
	return ""
}

func (x *Instrument) GetQtyStep() string {
	if x != nil {
		return x.QtyStep
	}
	return ""
}

func (x *Instrument) GetMinQty() string {
	if x != nil && x.MinQty != nil {
		return *x.MinQty
	}
	return ""
}

func (x *Instrument) GetMaxQty() string {
	if x != nil && x.MaxQty != nil {
		return *x.MaxQty
	}
	return ""
}

func (x *Instrument) GetMinNotional() string {
	if x != nil && x.MinNotional != nil {
		return *x.MinNotional
	}
	return ""
}

func (x *Instrument) GetFundingIntervalSeconds() int64 {
	if x != nil && x.FundingIntervalSeconds != nil {
		return *x.FundingIntervalSeconds
	}
	return 0
}

func (x *Instrument) GetDelistingTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DelistingTime
	}
	return nil
}

func (x *Instrument) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Ticker struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Exchange             string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Market               string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Symbol               string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastPrice            string                 `protobuf:"bytes,4,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	BidPrice             *string                `protobuf:"bytes,5,opt,name=bid_price,json=bidPrice,proto3,oneof" json:"bid_price,omitempty"`
	BidSize              *string                `protobuf:"bytes,6,opt,name=bid_size,json=bidSize,proto3,oneof" json:"bid_size,omitempty"`
	AskPrice             *string                `protobuf:"bytes,7,opt,name=ask_price,json=askPrice,proto3,oneof" json:"ask_price,omitempty"`
	AskSize              *string                `protobuf:"bytes,8,opt,name=ask_size,json=askSize,proto3,oneof" json:"ask_size,omitempty"`
	FundingRate          *string                `protobuf:"bytes,9,opt,name=funding_rate,json=fundingRate,proto3,oneof" json:"funding_rate,omitempty"`
	NextFundingInSeconds *int64                 `protobuf:"varint,10,opt,name=next_funding_in_seconds,json=nextFundingInSeconds,proto3,oneof" json:"next_funding_in_seconds,omitempty"`
	FetchedAt            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{9}
}

func (x *Ticker) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Ticker) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *Ticker) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Ticker) GetLastPrice() string {
	if x != nil {
		return x.LastPrice
	}
	return ""
}

func (x *Ticker) GetBidPrice() string {
	if x != nil && x.BidPrice != nil {
		return *x.BidPrice
	}
	return ""
}

func (x *Ticker) GetBidSize() string {
	if x != nil && x.BidSize != nil {
		return *x.BidSize
	}
	return ""
}

func (x *Ticker) GetAskPrice() string {
	if x != nil && x.AskPrice != nil {
		return *x.AskPrice
	}
	return ""
}

func (x *Ticker) GetAskSize() string {
	if x != nil && x.AskSize != nil {
		return *x.AskSize
	}
	return ""
}

func (x *Ticker) GetFundingRate() string {
	if x != nil && x.FundingRate != nil {
		return *x.FundingRate
	}
	return ""
}

func (x *Ticker) GetNextFundingInSeconds() int64 {
	if x != nil && x.NextFundingInSeconds != nil {
		return *x.NextFundingInSeconds
	}
	return 0
}

func (x *Ticker) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

type MarketStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Market        string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Window        string                 `protobuf:"bytes,4,opt,name=window,proto3" json:"window,omitempty"`
	High          string                 `protobuf:"bytes,5,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,6,opt,name=low,proto3" json:"low,omitempty"`
	Volume        string                 `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Turnover      string                 `protobuf:"bytes,8,opt,name=turnover,proto3" json:"turnover,omitempty"`
	PriceChange   *string                `protobuf:"bytes,9,opt,name=price_change,json=priceChange,proto3,oneof" json:"price_change,omitempty"`
	TradeCount    *int64                 `protobuf:"varint,10,opt,name=trade_count,json=tradeCount,proto3,oneof" json:"trade_count,omitempty"`
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketStats) Reset() {
	*x = MarketStats{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketStats) ProtoMessage() {}

func (x *MarketStats) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketStats.ProtoReflect.Descriptor instead.
func (*MarketStats) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{10}
}

func (x *MarketStats) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *MarketStats) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *MarketStats) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketStats) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *MarketStats) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *MarketStats) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *MarketStats) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *MarketStats) GetTurnover() string {
	if x != nil {
		return x.Turnover
	}
	return ""
}

func (x *MarketStats) GetPriceChange() string {
	if x != nil && x.PriceChange != nil {
		return *x.PriceChange
	}
	return ""
}

func (x *MarketStats) GetTradeCount() int64 {
	if x != nil && x.TradeCount != nil {
		return *x.TradeCount
	}
	return 0
}

func (x *MarketStats) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

type Kline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenTime      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	Open          string                 `protobuf:"bytes,3,opt,name=open,proto3" json:"open,omitempty"`
	High          string                 `protobuf:"bytes,4,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,5,opt,name=low,proto3" json:"low,omitempty"`
	Close         string                 `protobuf:"bytes,6,opt,name=close,proto3" json:"close,omitempty"`
	Volume        string                 `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Turnover      string                 `protobuf:"bytes,8,opt,name=turnover,proto3" json:"turnover,omitempty"`
	TradesCount   *int64                 `protobuf:"varint,9,opt,name=trades_count,json=tradesCount,proto3,oneof" json:"trades_count,omitempty"`
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kline) Reset() {
	*x = Kline{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kline) ProtoMessage() {}

func (x *Kline) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kline.ProtoReflect.Descriptor instead.
func (*Kline) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{11}
}

func (x *Kline) GetOpenTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenTime
	}
	return nil
}

func (x *Kline) GetCloseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

func (x *Kline) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Kline) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Kline) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Kline) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *Kline) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Kline) GetTurnover() string {
	if x != nil {
		return x.Turnover
	}
	return ""
}

func (x *Kline) GetTradesCount() int64 {
	if x != nil && x.TradesCount != nil {
		return *x.TradesCount
	}
	return 0
}

func (x *Kline) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_marketdata_v1_market_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_market_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_market_data_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_marketdata_v1_market_data_proto protoreflect.FileDescriptor

const file_marketdata_v1_market_data_proto_rawDesc = "" +
	"\n" +
	"\x1fmarketdata/v1/market_data.proto\x12\rmarketdata.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n" +
	"\x16ListInstrumentsRequest\x12\x1f\n" +
	"\bexchange\x18\x01 \x01(\tH\x00R\bexchange\x88\x01\x01\x12\x1b\n" +
	"\x06market\x18\x02 \x01(\tH\x01R\x06market\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x03 \x01(\tH\x02R\x06symbol\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x03R\x06status\x88\x01\x01B\v\n" +
	"\t_exchangeB\t\n" +
	"\a_marketB\t\n" +
	"\a_symbolB\t\n" +
	"\a_status\"\x92\x01\n" +
	"\x12ListTickersRequest\x12\x1f\n" +
	"\bexchange\x18\x01 \x01(\tH\x00R\bexchange\x88\x01\x01\x12\x1b\n" +
	"\x06market\x18\x02 \x01(\tH\x01R\x06market\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x03 \x01(\tH\x02R\x06symbol\x88\x01\x01B\v\n" +
	"\t_exchangeB\t\n" +
	"\a_marketB\t\n" +
	"\a_symbol\"\xbe\x01\n" +
	"\x16ListMarketStatsRequest\x12\x1f\n" +
	"\bexchange\x18\x01 \x01(\tH\x00R\bexchange\x88\x01\x01\x12\x1b\n" +
	"\x06market\x18\x02 \x01(\tH\x01R\x06market\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x03 \x01(\tH\x02R\x06symbol\x88\x01\x01\x12\x1b\n" +
	"\x06window\x18\x04 \x01(\tH\x03R\x06window\x88\x01\x01B\v\n" +
	"\t_exchangeB\t\n" +
	"\a_marketB\t\n" +
	"\a_symbolB\t\n" +
	"\a_window\"\x9a\x02\n" +
	"\x10GetKlinesRequest\x12\x1f\n" +
	"\bexchange\x18\x01 \x01(\tH\x00R\bexchange\x88\x01\x01\x12\x1b\n" +
	"\x06market\x18\x02 \x01(\tH\x01R\x06market\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x03 \x01(\tH\x02R\x06symbol\x88\x01\x01\x12\x1f\n" +
	"\binterval\x18\x04 \x01(\tH\x03R\binterval\x88\x01\x01\x12.\n" +
	"\x04from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x02toB\v\n" +
	"\t_exchangeB\t\n" +
	"\a_marketB\t\n" +
	"\a_symbolB\v\n" +
	"\t_interval\"V\n" +
	"\x17ListInstrumentsResponse\x12;\n" +
	"\vinstruments\x18\x01 \x03(\v2\x19.marketdata.v1.InstrumentR\vinstruments\"F\n" +
	"\x13ListTickersResponse\x12/\n" +
	"\atickers\x18\x01 \x03(\v2\x15.marketdata.v1.TickerR\atickers\"X\n" +
	"\x17ListMarketStatsResponse\x12=\n" +
	"\fmarket_stats\x18\x01 \x03(\v2\x1a.marketdata.v1.MarketStatsR\vmarketStats\"\xa9\x01\n" +
	"\x11GetKlinesResponse\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\tR\binterval\x12,\n" +
	"\x06klines\x18\x05 \x03(\v2\x14.marketdata.v1.KlineR\x06klines\"\xd1\x04\n" +
	"\n" +
	"Instrument\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"base_asset\x18\x04 \x01(\tR\tbaseAsset\x12\x1f\n" +
	"\vquote_asset\x18\x05 \x01(\tR\n" +
	"quoteAsset\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"price_tick\x18\a \x01(\tR\tpriceTick\x12\x19\n" +
	"\bqty_step\x18\b \x01(\tR\aqtyStep\x12\x1c\n" +
	"\amin_qty\x18\t \x01(\tH\x00R\x06minQty\x88\x01\x01\x12\x1c\n" +
	"\amax_qty\x18\n" +
	" \x01(\tH\x01R\x06maxQty\x88\x01\x01\x12&\n" +
	"\fmin_notional\x18\v \x01(\tH\x02R\vminNotional\x88\x01\x01\x12=\n" +
	"\x18funding_interval_seconds\x18\f \x01(\x03H\x03R\x16fundingIntervalSeconds\x88\x01\x01\x12A\n" +
	"\x0edelisting_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\rdelistingTime\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\n" +
	"\n" +
	"\b_min_qtyB\n" +
	"\n" +
	"\b_max_qtyB\x0f\n" +
	"\r_min_notionalB\x1b\n" +
	"\x19_funding_interval_seconds\"\xf9\x03\n" +
	"\x06Ticker\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"last_price\x18\x04 \x01(\tR\tlastPrice\x12 \n" +
	"\tbid_price\x18\x05 \x01(\tH\x00R\bbidPrice\x88\x01\x01\x12\x1e\n" +
	"\bbid_size\x18\x06 \x01(\tH\x01R\abidSize\x88\x01\x01\x12 \n" +
	"\task_price\x18\a \x01(\tH\x02R\baskPrice\x88\x01\x01\x12\x1e\n" +
	"\bask_size\x18\b \x01(\tH\x03R\aaskSize\x88\x01\x01\x12&\n" +
	"\ffunding_rate\x18\t \x01(\tH\x04R\vfundingRate\x88\x01\x01\x12:\n" +
	"\x17next_funding_in_seconds\x18\n" +
	" \x01(\x03H\x05R\x14nextFundingInSeconds\x88\x01\x01\x129\n" +
	"\n" +
	"fetched_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAtB\f\n" +
	"\n" +
	"_bid_priceB\v\n" +
	"\t_bid_sizeB\f\n" +
	"\n" +
	"_ask_priceB\v\n" +
	"\t_ask_sizeB\x0f\n" +
	"\r_funding_rateB\x1a\n" +
	"\x18_next_funding_in_seconds\"\xf5\x02\n" +
	"\vMarketStats\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06window\x18\x04 \x01(\tR\x06window\x12\x12\n" +
	"\x04high\x18\x05 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\tR\x03low\x12\x16\n" +
	"\x06volume\x18\a \x01(\tR\x06volume\x12\x1a\n" +
	"\bturnover\x18\b \x01(\tR\bturnover\x12&\n" +
	"\fprice_change\x18\t \x01(\tH\x00R\vpriceChange\x88\x01\x01\x12$\n" +
	"\vtrade_count\x18\n" +
	" \x01(\x03H\x01R\n" +
	"tradeCount\x88\x01\x01\x129\n" +
	"\n" +
	"fetched_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAtB\x0f\n" +
	"\r_price_changeB\x0e\n" +
	"\f_trade_count\"\xf3\x02\n" +
	"\x05Kline\x127\n" +
	"\topen_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bopenTime\x129\n" +
	"\n" +
	"close_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcloseTime\x12\x12\n" +
	"\x04open\x18\x03 \x01(\tR\x04open\x12\x12\n" +
	"\x04high\x18\x04 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\tR\x03low\x12\x14\n" +
	"\x05close\x18\x06 \x01(\tR\x05close\x12\x16\n" +
	"\x06volume\x18\a \x01(\tR\x06volume\x12\x1a\n" +
	"\bturnover\x18\b \x01(\tR\bturnover\x12&\n" +
	"\ftrades_count\x18\t \x01(\x03H\x00R\vtradesCount\x88\x01\x01\x129\n" +
	"\n" +
	"fetched_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAtB\x0f\n" +
	"\r_trades_count\"%\n" +
	"\vErrorDetail\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2\xfd\x02\n" +
	"\x11MarketDataService\x12`\n" +
	"\x0fListInstruments\x12%.marketdata.v1.ListInstrumentsRequest\x1a&.marketdata.v1.ListInstrumentsResponse\x12T\n" +
	"\vListTickers\x12!.marketdata.v1.ListTickersRequest\x1a\".marketdata.v1.ListTickersResponse\x12`\n" +
	"\x0fListMarketStats\x12%.marketdata.v1.ListMarketStatsRequest\x1a&.marketdata.v1.ListMarketStatsResponse\x12N\n" +
	"\tGetKlines\x12\x1f.marketdata.v1.GetKlinesRequest\x1a .marketdata.v1.GetKlinesResponseBCZAgithub.com/imbpp123/market-data/api/go/marketdata/v1;marketdatav1b\x06proto3"

var (
	file_marketdata_v1_market_data_proto_rawDescOnce sync.Once
	file_marketdata_v1_market_data_proto_rawDescData []byte
)

func file_marketdata_v1_market_data_proto_rawDescGZIP() []byte {
	file_marketdata_v1_market_data_proto_rawDescOnce.Do(func() {
		file_marketdata_v1_market_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketdata_v1_market_data_proto_rawDesc), len(file_marketdata_v1_market_data_proto_rawDesc)))
	})
	return file_marketdata_v1_market_data_proto_rawDescData
}

var file_marketdata_v1_market_data_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_marketdata_v1_market_data_proto_goTypes = []any{
	(*ListInstrumentsRequest)(nil),  // 0: marketdata.v1.ListInstrumentsRequest
	(*ListTickersRequest)(nil),      // 1: marketdata.v1.ListTickersRequest
	(*ListMarketStatsRequest)(nil),  // 2: marketdata.v1.ListMarketStatsRequest
	(*GetKlinesRequest)(nil),        // 3: marketdata.v1.GetKlinesRequest
	(*ListInstrumentsResponse)(nil), // 4: marketdata.v1.ListInstrumentsResponse
	(*ListTickersResponse)(nil),     // 5: marketdata.v1.ListTickersResponse
	(*ListMarketStatsResponse)(nil), // 6: marketdata.v1.ListMarketStatsResponse
	(*GetKlinesResponse)(nil),       // 7: marketdata.v1.GetKlinesResponse
	(*Instrument)(nil),              // 8: marketdata.v1.Instrument
	(*Ticker)(nil),                  // 9: marketdata.v1.Ticker
	(*MarketStats)(nil),             // 10: marketdata.v1.MarketStats
	(*Kline)(nil),                   // 11: marketdata.v1.Kline
	(*ErrorDetail)(nil),             // 12: marketdata.v1.ErrorDetail
	(*timestamppb.Timestamp)(nil),   // 13: google.protobuf.Timestamp
}
var file_marketdata_v1_market_data_proto_depIdxs = []int32{
	13, // 0: marketdata.v1.GetKlinesRequest.from:type_name -> google.protobuf.Timestamp
	13, // 1: marketdata.v1.GetKlinesRequest.to:type_name -> google.protobuf.Timestamp
	8,  // 2: marketdata.v1.ListInstrumentsResponse.instruments:type_name -> marketdata.v1.Instrument
	9,  // 3: marketdata.v1.ListTickersResponse.tickers:type_name -> marketdata.v1.Ticker
	10, // 4: marketdata.v1.ListMarketStatsResponse.market_stats:type_name -> marketdata.v1.MarketStats
	11, // 5: marketdata.v1.GetKlinesResponse.klines:type_name -> marketdata.v1.Kline
	13, // 6: marketdata.v1.Instrument.delisting_time:type_name -> google.protobuf.Timestamp
	13, // 7: marketdata.v1.Instrument.updated_at:type_name -> google.protobuf.Timestamp
	13, // 8: marketdata.v1.Ticker.fetched_at:type_name -> google.protobuf.Timestamp
	13, // 9: marketdata.v1.MarketStats.fetched_at:type_name -> google.protobuf.Timestamp
	13, // 10: marketdata.v1.Kline.open_time:type_name -> google.protobuf.Timestamp
	13, // 11: marketdata.v1.Kline.close_time:type_name -> google.protobuf.Timestamp
	13, // 12: marketdata.v1.Kline.fetched_at:type_name -> google.protobuf.Timestamp
	0,  // 13: marketdata.v1.MarketDataService.ListInstruments:input_type -> marketdata.v1.ListInstrumentsRequest
	1,  // 14: marketdata.v1.MarketDataService.ListTickers:input_type -> marketdata.v1.ListTickersRequest
	2,  // 15: marketdata.v1.MarketDataService.ListMarketStats:input_type -> marketdata.v1.ListMarketStatsRequest
	3,  // 16: marketdata.v1.MarketDataService.GetKlines:input_type -> marketdata.v1.GetKlinesRequest
	4,  // 17: marketdata.v1.MarketDataService.ListInstruments:output_type -> marketdata.v1.ListInstrumentsResponse
	5,  // 18: marketdata.v1.MarketDataService.ListTickers:output_type -> marketdata.v1.ListTickersResponse
	6,  // 19: marketdata.v1.MarketDataService.ListMarketStats:output_type -> marketdata.v1.ListMarketStatsResponse
	7,  // 20: marketdata.v1.MarketDataService.GetKlines:output_type -> marketdata.v1.GetKlinesResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_marketdata_v1_market_data_proto_init() }
func file_marketdata_v1_market_data_proto_init() {
	if File_marketdata_v1_market_data_proto != nil {
		return
	}
	file_marketdata_v1_market_data_proto_msgTypes[0].OneofWrappers = []any{}
	file_marketdata_v1_market_data_proto_msgTypes[1].OneofWrappers = []any{}
	file_marketdata_v1_market_data_proto_msgTypes[2].OneofWrappers = []any{}
	file_marketdata_v1_market_data_proto_msgTypes[3].OneofWrappers = []any{}
	file_marketdata_v1_market_data_proto_msgTypes[8].OneofWrappers = []any{}
	file_marketdata_v1_market_data_proto_msgTypes[9].OneofWrappers = []any{}
	file_marketdata_v1_market_data_proto_msgTypes[10].OneofWrappers = []any{}
	file_marketdata_v1_market_data_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketdata_v1_market_data_proto_rawDesc), len(file_marketdata_v1_market_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketdata_v1_market_data_proto_goTypes,
		DependencyIndexes: file_marketdata_v1_market_data_proto_depIdxs,
		MessageInfos:      file_marketdata_v1_market_data_proto_msgTypes,
	}.Build()
	File_marketdata_v1_market_data_proto = out.File
	file_marketdata_v1_market_data_proto_goTypes = nil
	file_marketdata_v1_market_data_proto_depIdxs = nil
}
