# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from marketdata.v1 import market_data_pb2 as marketdata_dot_v1_dot_market__data__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in marketdata/v1/market_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListInstruments = channel.unary_unary(
                '/marketdata.v1.MarketDataService/ListInstruments',
                request_serializer=marketdata_dot_v1_dot_market__data__pb2.ListInstrumentsRequest.SerializeToString,
                response_deserializer=marketdata_dot_v1_dot_market__data__pb2.ListInstrumentsResponse.FromString,
                _registered_method=True)
        self.ListTickers = channel.unary_unary(
                '/marketdata.v1.MarketDataService/ListTickers',
                request_serializer=marketdata_dot_v1_dot_market__data__pb2.ListTickersRequest.SerializeToString,
                response_deserializer=marketdata_dot_v1_dot_market__data__pb2.ListTickersResponse.FromString,
                _registered_method=True)
        self.ListMarketStats = channel.unary_unary(
                '/marketdata.v1.MarketDataService/ListMarketStats',
                request_serializer=marketdata_dot_v1_dot_market__data__pb2.ListMarketStatsRequest.SerializeToString,
                response_deserializer=marketdata_dot_v1_dot_market__data__pb2.ListMarketStatsResponse.FromString,
                _registered_method=True)
        self.GetKlines = channel.unary_unary(
                '/marketdata.v1.MarketDataService/GetKlines',
                request_serializer=marketdata_dot_v1_dot_market__data__pb2.GetKlinesRequest.SerializeToString,
                response_deserializer=marketdata_dot_v1_dot_market__data__pb2.GetKlinesResponse.FromString,
                _registered_method=True)


class MarketDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListInstruments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTickers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMarketStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKlines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListInstruments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstruments,
                    request_deserializer=marketdata_dot_v1_dot_market__data__pb2.ListInstrumentsRequest.FromString,
                    response_serializer=marketdata_dot_v1_dot_market__data__pb2.ListInstrumentsResponse.SerializeToString,
            ),
            'ListTickers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTickers,
                    request_deserializer=marketdata_dot_v1_dot_market__data__pb2.ListTickersRequest.FromString,
                    response_serializer=marketdata_dot_v1_dot_market__data__pb2.ListTickersResponse.SerializeToString,
            ),
            'ListMarketStats': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMarketStats,
                    request_deserializer=marketdata_dot_v1_dot_market__data__pb2.ListMarketStatsRequest.FromString,
                    response_serializer=marketdata_dot_v1_dot_market__data__pb2.ListMarketStatsResponse.SerializeToString,
            ),
            'GetKlines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKlines,
                    request_deserializer=marketdata_dot_v1_dot_market__data__pb2.GetKlinesRequest.FromString,
                    response_serializer=marketdata_dot_v1_dot_market__data__pb2.GetKlinesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketdata.v1.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketdata.v1.MarketDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListInstruments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.v1.MarketDataService/ListInstruments',
            marketdata_dot_v1_dot_market__data__pb2.ListInstrumentsRequest.SerializeToString,
            marketdata_dot_v1_dot_market__data__pb2.ListInstrumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTickers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.v1.MarketDataService/ListTickers',
            marketdata_dot_v1_dot_market__data__pb2.ListTickersRequest.SerializeToString,
            marketdata_dot_v1_dot_market__data__pb2.ListTickersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMarketStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.v1.MarketDataService/ListMarketStats',
            marketdata_dot_v1_dot_market__data__pb2.ListMarketStatsRequest.SerializeToString,
            marketdata_dot_v1_dot_market__data__pb2.ListMarketStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKlines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.v1.MarketDataService/GetKlines',
            marketdata_dot_v1_dot_market__data__pb2.GetKlinesRequest.SerializeToString,
            marketdata_dot_v1_dot_market__data__pb2.GetKlinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
